apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/fjguadalixf/environment-thiefmica-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackName: kubernetes-workloads
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: winged-citron-247419
    envOrganisation: fjguadalixf
    gitServer: https://github.com
    helmTemplate: true
    importMode: YAML
    kubeProvider: gke
    pipelineUsername: fjguadalixf
    promotionEngine: Prow
    prowConfig: Legacy
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    storageLocations:
    - bucketUrl: gs://thiefmica-lts-0ed9b259-410e-4381-96c1-678fc294ad23
      classifier: default
    - bucketUrl: gs://thiefmica-lts-0ed9b259-410e-4381-96c1-678fc294ad23
      classifier: logs
    useGitOps: true
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
  webHookEngine: Prow
status: {}
